---
python_tools:
  - package: "ansible"
    version: "13.1.0"
    venv_name: "ansible"
    executables:
      [
        "ansible",
        "ansible-community",
        "ansible-config",
        "ansible-console",
        "ansible-doc",
        "ansible-galaxy",
        "ansible-inventory",
        "ansible-playbook",
        "ansible-pull",
        "ansible-test",
        "ansible-vault",
      ]
